#!/bin/bash

declare -a CMD
CMD+=("printf '\033[1;33m';")
CMD+=("date '+%b %d, %Y         %H : %M : %S' | figlet -w 65;")
CMD+=("printf '\033[0m';")
#CMD+=("cal")

date=$(date)
while [ "$date" = "$(date)" ]; do
	continue
done
watch --no-title --color --precise -n 1 "${CMD[@]}"