#!/bin/bash

declare -a CMD
CMD+=("printf '\033[1;33m';")
CMD+=("date '+%b %d, %Y         %H : %M : %S' | figlet -w 55;")
CMD+=("printf '\033[0m';")
#CMD+=("cal")

watch --no-title --color --precise -n 1 "${CMD[@]}"